### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by eidermar** [frakman1/lifxscreen2#1]
Thanks for sharing this.

I'm running this on OSX 10.11.2 and it always throws this error: 

AttributeError: 'module' object has no attribute 'find_bulbs'

Any Idea what might cause this? Can I provide any more Information to help finding the culprit?

Thank you!

**Comment by frakman1** [comment]
Can you copy and paste the entire output including the invocation please?
It sounds like it lazy lights hasn't been installed properly on your system if it is complaining about "find_bulbs".How did you install the pre-requisite components?

**Comment by eidermar** [comment]
thanks for the quick answer. here you go:

```
XXXMBP:~ xxx$ python /Users/xxx/Desktop/Privat/Apps/LIFX/lifxscreen2-master/lifxscreen2.py 
Traceback (most recent call last):
  File "/Users/xxx/Desktop/Privat/Apps/LIFX/lifxscreen2-master/lifxscreen2.py", line 31, in <module>
    bulbs = lazylights.find_bulbs(expected_bulbs=2,timeout=5)
AttributeError: 'module' object has no attribute 'find_bulbs'
```

I installed lazylights with: `pip install git+https://github.com/mpapi/lazylights`
colors via pip and PIL screengrabber was already installed from ages ago, dunno how.

Does that help? On the lazylights github issues I saw another guy having the same error. I posted the issue there as well, hope thats allright.

**Comment by frakman1** [comment]
I see what the problem is now. You are using the mainline/master branch from here:
https://github.com/mpapi/lazylights

What you really need, is to be using the version 2.0 branch here:
https://github.com/mpapi/lazylights/tree/2.0

So now you need to delete any all all references to lazy lights and re-install the one from the 2.0 branch. Use this command:

```
pip install git+https://github.com/mpapi/lazylights@2.0
```

**Comment by eidermar** [comment]
thanks frak. this solved the problem, but unfortunately renders a new one: 

`xxxMBP:~ xxx$ python /Users/xxx/Desktop/Privat/Apps/LIFX/lifxscreen2-master/lifxscreen2.py 
set([Bulb(gateway_mac='LIFXV2', mac='\xd0s\xd5\x11\xa1E', addr=('192.168.1.8', 56700)), Bulb(gateway_mac='LIFXV2', mac='\xd0s\xd5\x12\x06\xcd', addr=('192.168.1.14', 56700))])
2
Traceback (most recent call last):
  File "/Users/xxx/Desktop/Privat/Apps/LIFX/lifxscreen2-master/lifxscreen2.py", line 41, in <module>
    myBulb1 = createBulb('10.10.10.2','XX:XX:XX:XX:XX:XX')  #Bulb for left  side of screen
  File "/Users/xxx/Desktop/Privat/Apps/LIFX/lifxscreen2-master/lifxscreen2.py", line 27, in createBulb
    return lazylights.Bulb(b'LIFXV2', binascii.unhexlify(macString.replace(':', '')), (ip,port))
TypeError: Non-hexadecimal digit found`

As you can see I'm not a coder. Forgive me if I'm doing obvious nonsense. I really appreciate your help!!!

**Comment by frakman1** [comment]
No problem. I struggle with python too AND I'm a coder! haha

I see what the issue is. Perhaps I should have made it clearer in the notes or rearranged the code a bit because it's pretty hacked up right now. 

The problem is that I put place-holders for the MAC Addresses of the LIFX bulbs in the code that I published. (see line 41 and 42). Replace the **'XX:XX:XX:XX:XX:XX'** with the MAC addresses of your bulbs. You should be able to find the MAC Address on the bulb itself, or on your router page, or by using my iOS app [LIFX Ambience](http://lifx.technicallycorrectman.com/)

Alternatively, if you don't want to fiddle with all that and don't mind all the bulbs reacting together instead of split-screen, then just delete (or comment out with a # before each line) the lines 40 to 48.
Then change the references to **bulbs1** _(line108 and110)_ and **bulbs2** _(line 145 and 147)_ to **bulbs** and that will control all the bulbs it sees together instead of in two groups.

**Comment by eidermar** [comment]
Thanks again. Now I have it working. This is great stuff, although I was hoping the delay would be a little less obvious with the LAN protocol. Do you have any tips on how to reduce the delay (if there are any)? Next step: combine this with my kodi installation :-)

**Comment by frakman1** [comment]
Glad it finally worked for you! Hallalujah!

I actually don't have any delay. It has to do with how fast your WiFi network is.The time between successive samples is nearly instantaneous since it runs in a loop and the bulb supports up to 20 packet instructions a second.

However, if you mean the time it takes for the color to change, then I set that to 500ms (half a second) for a nice smooth transition effect. You can tweak that if you like by changing the **DURATION** constant on line 18. Making it too low made it super fast but too jerky in my opinion.

**Comment by eidermar** [comment]
Yup, I was able to play around with some of the parameters in the script. I really love it. You are right about the jerkiness when duration is set too low. There's one last thing I couldn't figure out though. When I try your script on a machine that is wired to the router via LAN cable (same network), the script seems to be unable to find the bulbs. I know other scripts can detect the bulbs also via LAN not only WiFi. Is this possible somehow? Sorry if I abuse this Issue for multiple questions, not the best practice at all, I know.

Thanks for your patience and support!

Edit: Forget about the last question about LAN. I was able to solve it!

**Comment by frakman1** [comment]
No problem. Hopefully, it will help others too.

How did you solve the LAN issue?

**Comment by eidermar** [comment]
Well, the LAN issue was probably related to my VPN. It has a kill switch that sometimes blocks netbios LAN traffic -> over-cautious. Once I pinged the lamps locally though the script discovered them just fine. So not the scripts fault at all. I wish my coding was more than the basic 101 of 20 years ago so I could dig deeper into that stuff myself. Have a great weekend!!!
